#ifndef _PACMAN_STATICSETTINGS_
#define _PACMAN_STATICSETTINGS_

#define OBJECT_DIMENSION 10

#define PACMAN_DETAIL 10
#define FOOD_DETAIL 10
#define PORTAL_DETAIL 10

#define GHOST_AMMOUNT 0

#define GATEOPENING_ANIMATION_DURATION 2000
#define WALKING_ANIMATION 200

#endif