#ifndef _PE_PCONSTANTS_
#define _PE_PCONSTANTS_

#include <math.h>

#define GRAVITATIONAL_CONSTANT (6.67300 * pow((double) 10, (double) -11))
#define EARTH_GRAVITY_ACCELERATION 9.807

#define SLIME_ON_CONCRETE_STATIC_FRICTION_COEFICIENT 0.20
#define SLIME_ON_CONCRETE_KINETIC_FRICTION_COEFICIENT (SLIME_ON_CONCRETE_STATIC_FRICTION_COEFICIENT / 1.5);

#endif